### ISSUE TITLE
Deformed shadows with Omni if the size of the cubemap ≠ screen size

### ISSUE THREAD

**Issue by phaazon** [phaazon/photon#23]
# Issue

When the size of the *shadow cubemap* of an `Omni` and the dimensions of the screen are not all the same, such as **1024 / 1024x1024**, the shadows is deformed and totally fucked up.

# How to reproduce

Simply put different sizes and dimensions. A good way to witness the error:

  - shadow cubemap size set to **2048**
  - screen dimensions set to **1024x1024**

# Directions and leads

So far, I haven’t investigated yet. I don’t really understand how the cubemap’s size may change the aspect of the shadows, even displace it, since its size only affects its quality – the more it is, the more accurate the shadows are.

### 12:11 AM

@xtrium-lnx pointed out the fact the viewport should be changed. Indeed, the viewport is set at top-level [here](https://github.com/phaazon/photon/blob/master/src/Photon/Render/Forward/IO.hs#L31). We might need to put a similar call when rendering to the shadowing framebuffer.

**Comment by xtrium-lnx** [comment]
Don't forget to update the viewport when (un)binding the framebuffer. It should reflect the size of the texture you're rendering into - that's even more true when the w/h ratio changes because then it also distorts the render.

If it doesn't reflect the currently bound fbo's size, it will most probably distort and move away from the center.

**Comment by phaazon** [comment]
Oh, it might be that, yeah, since I use `glViewport` at top-level! I’ll try that, thanks!

**Comment by phaazon** [comment]
f9cc14edf69d0086c5d6c29d80f7d7e134d22743 fixed that.
